name: Boto3 Batch Utils
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with .flake8
      run: |
        pip install flake8
        flake8 .
    - name: Test with nose
      run: |
        pip install nose
        pip install coverage
        nosetests tests/ --with-coverage --cover-min 85 --cover-package=boto3_batch_utils
